#! /bin/sh

#Startup thing
pgrep -x sxhkd > /dev/null || sxhkd                                             &
picom -b --config ~/.config/picom.conf                                          &
feh --no-feh --bg-scale .themes/Catppuccin-green/wallpapers/void-chan.png       &
xsetroot -cursor_name left_ptr                                                  &
ibus-daemon -dxrR                                                               &
dunst                                                                           &
~/.config/polybar/launch.sh                                                     &
pipewire                                                                        &
pipewire-pulse                                                                  &

wmname LG3D

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config left_padding                0
bspc config bottom_padding              0
bspc config top_padding                 0
bspc config right_padding               0

bspc config left_monocle_padding        0
bspc config bottom_monocle_padding      0
bspc config top_monocle_padding         0
bspc config right_monocle_padding       0

bspc config window_gap                  7

bspc config border_width                2
bspc config normal_border_color         "#626880"
bspc config focused_border_color        "#81C8BE"
bspc config active_border_color         "#81C8BE"
bspc config presel_feedback_color       "#R5C890"

bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner

bspc config split_ratio                 0.52
bspc config borderless_monocle          true
bspc config gapless_monocle             false

